### ISSUE TITLE
Better naming for 'r' params

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#9]
Throughout surge we overload the name `r` to mean various different verifier (fiat-shamir) provided randomness. 

We should standardize the naming of these different `r` parameters and clean up the references.

**Comment by wyattbenno777** [comment]
Going to add this here as it is about naming.

It seems that the naming of the polynomials may have been mixed up / are not clear.

In the write up c-variate poly contain the final reads.
But in the code it is named log_m_variate.
https://github.com/a16z/Lasso/blob/cc5f85a561b1287f82154bca453b0b1113b86b1f/src/lasso/densified.rs#L62

https://github.com/a16z/Lasso/blob/master/EngineeringOverview.md

While the variable named l_variate_polys contains :

-   $`\text{dim}_1, ... \text{dim}_c`$: Purported subtable lookup indices
-   $E_1,...,E_\alpha$
-   $`\text{read\_counts}_{1},...,\text{read\_counts}_{\alpha}`$

In the paper it also seems to follow the write-up naming rather than the naming in code.
https://people.cs.georgetown.edu/jthaler/Lasso-paper.pdf

**Comment by moodlezoup** [comment]
To clarify, the `final` polynomials are log(M)-variate, where M = N^(1/C) is the memory size. 
log(M) = log(N)/C so I think the variable name / engineering overview / paper are consistent with one another, though I suppose it might be clearer if the "m" was capitalized in the variable name, i.e. `combined_log_M_variate_polys`?

**Comment by wyattbenno777** [comment]
`log(M) = log(N)/C`
`combined_log_M_variate_polys`
Makes sense! 

Possibly just even a comment above it would work.
https://github.com/a16z/Lasso/blob/e52d160c44b701f538de39b29502546f85af4ac6/src/lasso/densified.rs#L62
